[package]
name = "tantivy-cli"
version = "0.4.0-alpha"
authors = ["Paul Masurel <paul.masurel@gmail.com>"]

description = """Command line interface for Tantivy, a search engine library."""
documentation = "https://github.com/tantivy-search/tantivy-cli"
homepage = "https://github.com/tantivy-search/tantivy-cli"
repository = "https://github.com/tantivy-search/tantivy-cli"

readme = "README.md"
keywords = ["search", "information", "retrieval"]
license = "MIT"

[dependencies]
time = "0.1"
iron = "0.4"
staticfile = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
persistent="0.2"
clap = "2"
ansi_term = "0.8"
urlencoded = "0.4"
mount = "0.2"
chan = "0.1"
bincode = "0.4"
byteorder = "0.5"
log = "0.3"
env_logger = "0.3"
version = "2"
tantivy = { path="../tantivy", branch="tantivy-imhotep", features=["streamdict"]}
futures = "0.1"
#tantivy = "0.3.1"

[[bin]]
name = "tantivy"
path = "src/main.rs"


[profile.release]
opt-level = 3
#debug = true
debug-assertions = false
lto = true


[features]
default = ["tantivy/simdcompression"]

